from tensorflow/tensorflow:latest-gpu-py3
  
RUN apt-get update && apt-get install -y --no-install-recommends \
git

RUN pip3 install \
tensorflow-gpu==1.14 \
tqdm \
scikit-image==0.15.0 \
natsort \
numpy==1.16.5

